SET TRANSACTION NAME 'comp322_s2021115360_donghyeok_seo';
CREATE TABLE BOOK(
    BOOKID NUMBER PRIMARY KEY NOT NULL ,
    BOOKNAME VARCHAR(100) ,
    PUBLISHER VARCHAR2(20) ,
    PRICE NUMBER
);
SAVEPOINT CREATE_TABLE;

INSERT INTO BOOK VALUES (1, 'Database', 'Pearson', 30000);
SELECT BOOKNAME B1 FROM BOOK WHERE BOOKID = 1;
SAVEPOINT INSERT_1;

UPDATE BOOK SET BOOKNAME = 'Introduction to database' WHERE BOOKID = 1;
SELECT BOOKNAME B2 FROM BOOK WHERE BOOKID = 1;
SAVEPOINT UPDATE_1;

UPDATE BOOK SET BOOKNAME = 'Database Lab.' WHERE BOOKID = 1;
SELECT BOOKNAME B3 FROM BOOK WHERE BOOKID = 1;

ROLLBACK TO UPDATE_1;
SELECT BOOKNAME B4 FROM BOOK WHERE BOOKID = 1;

ROLLBACK TO INSERT_1;
SELECT BOOKNAME B5 FROM BOOK WHERE BOOKID = 1;

COMMIT;

UPDATE BOOK SET BOOKNAME = 'Database Lab2.' WHERE BOOKID = 1;
SELECT BOOKNAME B6 FROM BOOK WHERE BOOKID = 1;

ROLLBACK;
SELECT BOOKNAME B7 FROM BOOK WHERE BOOKID = 1;

DELETE FROM BOOK WHERE BOOKID = 1;
SELECT BOOKNAME B8 FROM BOOK WHERE BOOKID = 1;

ROLLBACK;
SELECT BOOKNAME B9 FROM BOOK WHERE BOOKID = 1;

COMMIT;