-- lab5-2021115360.sql
-- 5-1
CREATE TABLE EMPLOYEE (
    Fname VARCHAR(20) NOT NULL,
    Minit CHAR,
    Lname VARCHAR(20) NOT NULL,
    Ssn CHAR(9) NOT NULL,
    Bdate DATE,
    Address VARCHAR(50),
    Sex CHAR,
    Salary NUMBER,
    Super_ssn CHAR(9),
    Dno NUMBER(3, 0) NOT NULL,
    PRIMARY KEY (Ssn)
    );

CREATE TABLE DEPARTMENT (
    Dname VARCHAR(20) NOT NULL,
	Dnumber NUMBER(3, 0) NOT NULL,
	Mgr_ssn CHAR(9) NOT NULL,
	Mgr_start_date DATE,
    PRIMARY KEY (Dnumber),
    UNIQUE (Dname)
    );

CREATE TABLE DEPT_LOCATION (
    Dnumber NUMBER(3, 0) NOT NULL,
	Dlocation VARCHAR(20) NOT NULL,
    PRIMARY KEY (Dnumber, Dlocation)
    );

CREATE TABLE WORKS_ON (
    Essn CHAR(9) NOT NULL,
    Pno NUMBER(3, 0) NOT NULL,
    Hours NUMBER(3, 1),
    PRIMARY KEY (Essn, Pno)
    );

CREATE TABLE PROJECT (
    Pname VARCHAR(20) NOT NULL,
	Pnumber NUMBER(3, 0) NOT NULL,
	Plocation VARCHAR(20),
	Dnum NUMBER(3, 0) NOT NULL,
    PRIMARY KEY (Pnumber),
    UNIQUE (Pname)
    );

CREATE TABLE DEPENDENT (
    Essn CHAR(9) NOT NULL,
	Dependent_name VARCHAR(20) NOT NULL,
	Sex CHAR,
	Bdate DATE,
	Relationship VARCHAR(20),
    PRIMARY KEY (Essn, Dependent_name)
    );

ALTER TABLE EMPLOYEE ADD (
    FOREIGN KEY (Super_ssn) REFERENCES EMPLOYEE(Ssn),
    FOREIGN KEY (Dno) REFERENCES DEPARTMENT(Dnumber)
);

ALTER TABLE DEPARTMENT ADD (
    FOREIGN KEY (Mgr_ssn) REFERENCES EMPLOYEE(Ssn)
);

ALTER TABLE DEPT_LOCATION ADD (
    FOREIGN KEY (Dnumber) REFERENCES DEPARTMENT(Dnumber)
);

ALTER TABLE WORKS_ON ADD (
    FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn),
    FOREIGN KEY (Pno) REFERENCES PROJECT(Pnumber)
    );

ALTER TABLE PROJECT ADD (
    FOREIGN KEY (Dnum) REFERENCES DEPARTMENT(DNUMBER)
    );

ALTER TABLE DEPENDENT ADD (
    FOREIGN KEY (Essn) REFERENCES EMPLOYEE(Ssn)
    );

commit;

-- 5-2
ALTER TABLE DEPARTMENT MODIFY Mgr_ssn NULL;
-- FOR INSERT DEPARTMENT, INDEPENDENT TO CONSTRAINT
commit;

INSERT INTO DEPARTMENT (DNAME, DNUMBER, MGR_SSN, MGR_START_DATE)
VALUES
    ('Research',
     5,
     NULL,
     '1988-05-22'
    );

INSERT INTO DEPARTMENT (DNAME, DNUMBER, MGR_SSN, MGR_START_DATE)
VALUES
    ('Administration',
     4,
     NULL,
     '1995-01-01'
    );

INSERT INTO DEPARTMENT (DNAME, DNUMBER, MGR_SSN, MGR_START_DATE)
VALUES
    ('Headquarters',
     1,
     NULL,
     '1988-05-22'
    );

commit;

INSERT INTO EMPLOYEE
    (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPER_SSN, DNO)
VALUES
    ('John',
     'B',
     'Smith',
     '123456789',
     '1965-01-09',
     '731 Fondren, Houston, TX',
     'M',
     30000,
     NULL,
     5
    );

INSERT INTO EMPLOYEE
    (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPER_SSN, DNO)
VALUES
    ('Franklin',
     'T',
     'Wong',
     '333445555',
     '1955-12-08',
     '638 Voss, Houston, TX',
     'M',
     40000,
     NULL,
     5
    );

INSERT INTO EMPLOYEE
    (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPER_SSN, DNO)
VALUES
    ('Alica',
     'J',
     'Zelaya',
     '999887777',
     '1968-01-09',
     '3321 Castle, Spring, TX',
     'F',
     25000,
     NULL,
     4
    );

INSERT INTO EMPLOYEE
    (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPER_SSN, DNO)
VALUES
    ('Jennifer',
     'S',
     'Wallace',
     '987654321',
     '1941-06-20',
     '291 Berry, Bellaire, TX',
     'F',
     43000,
     NULL,
     4
    );

INSERT INTO EMPLOYEE
    (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPER_SSN, DNO)
VALUES
    ('Ramesh',
     'K',
     'Narayan',
     '666884444',
     '1962-09-15',
     '975 Fire Oak, Humble, TX',
     'M',
     38000,
     NULL,
     5
    );

INSERT INTO EMPLOYEE
    (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPER_SSN, DNO)
VALUES
    ('Joyce',
     'A',
     'English',
     '453453453',
     '1972-07-31',
     '5631 rice, Houston, TX',
     'F',
     25000,
     NULL,
     5
    );

INSERT INTO EMPLOYEE
    (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPER_SSN, DNO)
VALUES
    ('Ahmad',
     'V',
     'Jabbar',
     '987987987',
     '1969-03-29',
     '980 Dallas, Houston, TX',
     'M',
     25000,
     NULL,
     4
    );

INSERT INTO EMPLOYEE
    (FNAME, MINIT, LNAME, SSN, BDATE, ADDRESS, SEX, SALARY, SUPER_SSN, DNO)
VALUES
    ('James',
     'E',
     'Borg',
     '888665555',
     '1937-11-10',
     '450 Stone, Houston, TX',
     'M',
     55000,
     NULL,
     1
    );

commit;

UPDATE EMPLOYEE
SET SUPER_SSN = '333445555'
WHERE SSN = '123456789';

UPDATE EMPLOYEE
SET SUPER_SSN = '888665555'
WHERE SSN = '333445555';

UPDATE EMPLOYEE
SET SUPER_SSN = '987654321'
WHERE SSN = '999887777';

UPDATE EMPLOYEE
SET SUPER_SSN = '888665555'
WHERE SSN = '987654321';

UPDATE EMPLOYEE
SET SUPER_SSN = '333445555'
WHERE SSN = '666884444';

UPDATE EMPLOYEE
SET SUPER_SSN = '333445555'
WHERE SSN = '453453453';

UPDATE EMPLOYEE
SET SUPER_SSN = '987654321'
WHERE SSN = '987987987';

UPDATE DEPARTMENT
SET MGR_SSN = '333445555'
WHERE DNUMBER = 5;

UPDATE DEPARTMENT
SET MGR_SSN = '987654321'
WHERE DNUMBER = 4;

UPDATE DEPARTMENT
SET MGR_SSN = '888665555'
WHERE DNUMBER = 1;

commit;

ALTER TABLE DEPARTMENT MODIFY MGR_SSN NOT NULL;
-- AFTER INSERT, SET NOT NULL
commit;

INSERT INTO DEPT_LOCATION (DNUMBER, DLOCATION)
VALUES (1, 'Houston');

INSERT INTO DEPT_LOCATION (DNUMBER, DLOCATION)
VALUES (4, 'Stafford');

INSERT INTO DEPT_LOCATION (DNUMBER, DLOCATION)
VALUES (5, 'Bellaire');

INSERT INTO DEPT_LOCATION (DNUMBER, DLOCATION)
VALUES (5, 'Sugarland');

INSERT INTO DEPT_LOCATION (DNUMBER, DLOCATION)
VALUES (5, 'Houston');

INSERT INTO PROJECT (PNAME, PNUMBER, PLOCATION, DNUM)
VALUES ('ProductX', 1, 'Bellaire', 5);

INSERT INTO PROJECT (PNAME, PNUMBER, PLOCATION, DNUM)
VALUES ('ProductY', 2, 'Sugarland', 5);

INSERT INTO PROJECT (PNAME, PNUMBER, PLOCATION, DNUM)
VALUES ('ProductZ', 3, 'Houston', 5);

INSERT INTO PROJECT (PNAME, PNUMBER, PLOCATION, DNUM)
VALUES ('Computerization', 10, 'Stafford', 4);

INSERT INTO PROJECT (PNAME, PNUMBER, PLOCATION, DNUM)
VALUES ('Reorganization', 20, 'Houston', 1);

INSERT INTO PROJECT (PNAME, PNUMBER, PLOCATION, DNUM)
VALUES ('Newbenefits', 30, 'Stafford', 4);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('123456789', 1, 32.5);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('123456789', 2, 7.5);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('666884444', 3, 40.0);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('453453453', 1, 20.0);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('453453453', 2, 20.0);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('333445555', 2, 10.0);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('333445555', 3, 10.0);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('333445555', 10, 10.0);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('333445555', 20, 10.0);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('999887777', 30, 30.0);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('999887777', 10, 10.0);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('987987987', 10, 35.0);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('987987987', 30, 5.0);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('987654321', 30, 20.0);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('987654321', 20, 15.0);

INSERT INTO WORKS_ON (ESSN, PNO, HOURS)
VALUES ('888665555', 20, NULL);

INSERT INTO DEPENDENT (ESSN, DEPENDENT_NAME, SEX, BDATE, RELATIONSHIP)
VALUES ('333445555', 'Alice', 'F', '1986-04-05', 'Daughter');

INSERT INTO DEPENDENT (ESSN, DEPENDENT_NAME, SEX, BDATE, RELATIONSHIP)
VALUES ('333445555', 'Theodore', 'M', '1983-10-25', 'Son');

INSERT INTO DEPENDENT (ESSN, DEPENDENT_NAME, SEX, BDATE, RELATIONSHIP)
VALUES ('333445555', 'Joy', 'F', '1958-05-03', 'Spouse');

INSERT INTO DEPENDENT (ESSN, DEPENDENT_NAME, SEX, BDATE, RELATIONSHIP)
VALUES ('987654321', 'Abner', 'M', '1942-02-28', 'Spouse');

INSERT INTO DEPENDENT (ESSN, DEPENDENT_NAME, SEX, BDATE, RELATIONSHIP)
VALUES ('123456789', 'Michael', 'M', '1988-01-04', 'Son');

INSERT INTO DEPENDENT (ESSN, DEPENDENT_NAME, SEX, BDATE, RELATIONSHIP)
VALUES ('123456789', 'Alice', 'F', '1988-12-30', 'Daughter');

INSERT INTO DEPENDENT (ESSN, DEPENDENT_NAME, SEX, BDATE, RELATIONSHIP)
VALUES ('123456789', 'Elizabeth', 'F', '1967-05-05', 'Spouse');

commit;

-- 5-3 Q1
SELECT FNAME,LNAME,SALARY
FROM EMPLOYEE
WHERE DNO = 5
ORDER BY SALARY DESC;

-- 5-3 Q2
SELECT DNAME, SSN, FNAME, LNAME
FROM EMPLOYEE INNER JOIN DEPARTMENT on EMPLOYEE.DNO = DEPARTMENT.DNUMBER
WHERE INSTR(EMPLOYEE.ADDRESS, 'Houston') > 0 AND EMPLOYEE.SUPER_SSN = '987654321';

-- 5-3 Q3
SELECT FNAME, LNAME, HOURS
FROM EMPLOYEE A INNER JOIN (
    SELECT ESSN, HOURS
    FROM WORKS_ON INNER JOIN PROJECT ON WORKS_ON.PNO = PROJECT.PNUMBER
    WHERE HOURS >= 2.0 AND PROJECT.PNAME ='Newbenefits'
    ) B ON A.SSN = B.ESSN
ORDER BY HOURS ASC;

-- 5-3 Q4
SELECT E.FNAME, E.LNAME, D.DNAME
FROM EMPLOYEE E, DEPARTMENT D
WHERE (
    SSN IN (
        SELECT DISTINCT ESSN
        FROM WORKS_ON W INNER JOIN (
            SELECT PNUMBER
            FROM PROJECT P
            WHERE INSTR(P.PNAME, 'Product') > 0
            ) X ON W.PNO = X.PNUMBER
        WHERE W.HOURS >= 10
        )
    ) AND D.DNUMBER = E.DNO
ORDER BY E.LNAME ASC;

-- 5-3 Q5
SELECT DNAME, LNAME, FNAME, DEPENDENT_NAME
FROM EMPLOYEE E
    INNER JOIN DEPARTMENT D ON D.DNUMBER = E.DNO
    INNER JOIN DEPENDENT DP ON DP.ESSN = E.SSN
WHERE E.SSN IN (
    SELECT SSN
    FROM EMPLOYEE
    WHERE SUPER_SSN = '888665555'
    ) AND DP.RELATIONSHIP = 'Spouse';

-- 5-4 D1
DELETE FROM DEPENDENT
WHERE RELATIONSHIP = 'Son' AND ESSN = '333445555';

SELECT *
FROM DEPENDENT;

ROLLBACK ;

-- 5-4 D2 : error. 무결성 제약조건 위배 - 자식 레코드가 존재하는데 부모 레코드 update
/*DELETE FROM DEPARTMENT
WHERE DNUMBER = 4;

-- 5-4 D3
DELETE FROM WORKS_ON
WHERE PNO = 10 AND HOURS >= 30;

SELECT *
FROM WORKS_ON;

ROLLBACK ;*/

-- 5-5 U1
UPDATE PROJECT SET PLOCATION = 'Daegu'
WHERE DNUM = 5;

SELECT *
FROM PROJECT
WHERE DNUM = 5;

ROLLBACK ;

-- 5-5 U2 : error. EMPLOYEE.SSN에 존재하지 않아 참조 불가 - '1112233445'라는 부모키 존재하지 않음
/*UPDATE EMPLOYEE SET SUPER_SSN = '112233445'
WHERE DNO = 4;

SELECT *
FROM EMPLOYEE;

ROLLBACK ;*/

-- 5-5 U3 : error. 무결성 제약 조건 위배 - 자식 키에서 참조 중인 부모 키 수정
/*UPDATE DEPARTMENT SET DNAME = 'Research'
WHERE DNUMBER = 1;

SELECT *
FROM DEPARTMENT;

ROLLBACK ;*/