-- Team6 DDL

CREATE TABLE USERS(
    ID_NUMBER CHAR(12) NOT NULL , -- 11 DIGIT
    NAME VARCHAR2(30) NOT NULL ,
    SEX CHAR(1) NOT NULL , -- 'M' OR 'F'
    YOB CHAR(4) , -- ONLY YEAR
    JOB VARCHAR2(100) ,
    CHECK ( ID_NUMBER LIKE 'U%') ,
    CHECK ( ID_NUMBER LIKE '____-__-____') ,
    CHECK ( SEX LIKE 'M' OR SEX LIKE 'F') ,
    PRIMARY KEY (ID_NUMBER)
);

CREATE TABLE MANAGER(
    ID_NUMBER CHAR(12) NOT NULL ,
    BANK_ACCOUNT VARCHAR2(20) NOT NULL ,
    PRIMARY KEY (ID_NUMBER)
);

CREATE TABLE MEMBER(
    ID_NUMBER CHAR(12) NOT NULL ,
    PREPAID_MONEY NUMBER ,
    PRIMARY KEY (ID_NUMBER)
);

CREATE TABLE MAN_EVAL_MEM(
    MEM_ID CHAR(12) NOT NULL ,
    MAN_ID CHAR(12) NOT NULL ,
    EVAL_TIER CHAR(1) ,
    UPDATE_TIME DATE ,
    PRIMARY KEY (MEM_ID, MAN_ID)
);

CREATE TABLE TEAM(
    TEAM_ID CHAR(12) NOT NULL ,
    TEAM_NAME VARCHAR2(20) NOT NULL ,
    CHECK ( TEAM_ID LIKE '____-__-____') ,
    CHECK ( TEAM_ID LIKE 'T%') ,
    PRIMARY KEY (TEAM_ID)
);

CREATE TABLE TEAM_MEM(
    TEAM_ID CHAR(12) NOT NULL ,
    MEM_ID CHAR(12) NOT NULL ,
    PRIMARY KEY (TEAM_ID, MEM_ID)
);

CREATE TABLE TRAINING(
    CLASS_ID CHAR(12) NOT NULL ,
    DATE_TIME DATE NOT NULL ,
    TUTOR_ID CHAR(12) NOT NULL ,
    PRIMARY KEY (CLASS_ID)
);

CREATE TABLE TRAIN_ENROLLS(
    CLASS_ID CHAR(12) NOT NULL ,
    TUTEE_ID CHAR(12) NOT NULL ,
    PRIMARY KEY (CLASS_ID, TUTEE_ID)
);

CREATE TABLE TRAIN_REG(
    CLASS_ID CHAR(12) NOT NULL ,
    RECOMMEND_TIER CHAR(1) NOT NULL ,
    SUBJECT VARCHAR2(20) ,
    PLACE VARCHAR2(100) ,
    MAX_NUM NUMBER NOT NULL ,
    WAGE NUMBER ,
    PRIMARY KEY (CLASS_ID)
);

CREATE TABLE MATCH(
    MATCH_ID CHAR(12) NOT NULL ,
    DATE_TIME DATE NOT NULL ,
    PLACE_ID CHAR(13) NOT NULL ,
    TYPE CHAR(1) NOT NULL , -- 'A' = FUTSAL, 'B' = SOCCER
    SEX_CONSTRAINT CHAR(1) , -- 'M' = ONLY MALE, 'F' = ONLY FEMALE, NULL = NO RESTRICT
    CHECK ( TYPE LIKE 'F' OR TYPE LIKE 'S') ,
    CHECK ( MATCH_ID LIKE '____-__-____') ,
    CHECK ( MATCH_ID LIKE 'M%') ,
    PRIMARY KEY (MATCH_ID)
);

CREATE TABLE MATCH_APP_MEMBER(
    MATCH_ID CHAR(12) NOT NULL ,
    MEMBER_ID CHAR(12) NOT NULL ,
    COST NUMBER ,
    PRIMARY KEY (MATCH_ID, MEMBER_ID)
);

CREATE TABLE MATCH_APP_MANAGER(
    MATCH_ID CHAR(12) NOT NULL ,
    MANAGER_ID CHAR(12) NOT NULL ,
    WAGE NUMBER ,
    PRIMARY KEY (MATCH_ID, MANAGER_ID)
);

CREATE TABLE FIELD(
    FIELD_ID CHAR(13) NOT NULL ,
    NAME VARCHAR2(20) NOT NULL ,
    FIELD_HP VARCHAR2(20) ,
    OWNER_HP VARCHAR2(20) NOT NULL ,
    ADDRESS VARCHAR2(100) NOT NULL ,
    CHECK ( FIELD_ID LIKE '_____-__-____') ,
    CHECK ( FIELD_ID LIKE 'F%') ,
    PRIMARY KEY (FIELD_ID)
);

CREATE TABLE OWNER(
    OWNER_HP VARCHAR2(20) NOT NULL ,
    NAME VARCHAR2(20) NOT NULL ,
    PRIMARY KEY (OWNER_HP)
);

COMMIT;

ALTER TABLE MANAGER ADD (
    FOREIGN KEY (ID_NUMBER) REFERENCES USERS (ID_NUMBER) ON DELETE CASCADE
    );

ALTER TABLE MEMBER ADD (
    FOREIGN KEY (ID_NUMBER) REFERENCES USERS (ID_NUMBER) ON DELETE CASCADE
    );

ALTER TABLE MAN_EVAL_MEM ADD(
    FOREIGN KEY (MEM_ID) REFERENCES MEMBER (ID_NUMBER) ON DELETE CASCADE,
    FOREIGN KEY (MAN_ID) REFERENCES MANAGER (ID_NUMBER) ON DELETE CASCADE
    );

CREATE OR REPLACE VIEW MEMBER_EVAL_VIEW AS
    SELECT MEM_ID, CHR(AVG(ASCII(EVAL_TIER))) AS TIER
    FROM MAN_EVAL_MEM
    WHERE UPDATE_TIME - SYSDATE <= 20
    GROUP BY MEM_ID;

ALTER TABLE TEAM_MEM ADD(
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM (TEAM_ID) ON DELETE CASCADE,
    FOREIGN KEY (MEM_ID) REFERENCES MEMBER (ID_NUMBER) ON DELETE CASCADE
    );

CREATE OR REPLACE VIEW TEAM_EVAL_VIEW AS
    SELECT TEAM_ID, CHR(AVG(ASCII(TIER))) AS TEAM_TIER
    FROM TEAM_MEM TM INNER JOIN MEMBER_EVAL_VIEW EV ON TM.MEM_ID = EV.MEM_ID
    GROUP BY TEAM_ID;

ALTER TABLE TRAINING ADD (
    FOREIGN KEY (TUTOR_ID) REFERENCES MEMBER (ID_NUMBER) ON DELETE CASCADE
    );

ALTER TABLE TRAIN_ENROLLS ADD(
    FOREIGN KEY (CLASS_ID) REFERENCES TRAINING (CLASS_ID) ON DELETE CASCADE,
    FOREIGN KEY (TUTEE_ID) REFERENCES MEMBER (ID_NUMBER) ON DELETE CASCADE
    );

ALTER TABLE TRAIN_REG ADD(
    FOREIGN KEY (CLASS_ID) REFERENCES TRAINING (CLASS_ID) ON DELETE CASCADE
    );

ALTER TABLE MATCH ADD(
    FOREIGN KEY (PLACE_ID) REFERENCES FIELD (FIELD_ID) ON DELETE CASCADE
    );

CREATE OR REPLACE VIEW MATCH_EVAL_VIEW AS
    SELECT MATCH_ID, CHR(AVG(ASCII(TIER))) AS MATCH_TIER
    FROM MATCH_APP_MEMBER AP INNER JOIN MEMBER_EVAL_VIEW EV ON AP.MEMBER_ID = EV.MEM_ID
    GROUP BY MATCH_ID;

ALTER TABLE MATCH_APP_MEMBER ADD(
    FOREIGN KEY (MATCH_ID) REFERENCES MATCH (MATCH_ID) ON DELETE CASCADE,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID_NUMBER) ON DELETE CASCADE
    );

ALTER TABLE MATCH_APP_MANAGER ADD(
    FOREIGN KEY (MATCH_ID) REFERENCES MATCH (MATCH_ID) ON DELETE CASCADE,
    FOREIGN KEY (MANAGER_ID) REFERENCES MANAGER (ID_NUMBER) ON DELETE CASCADE
    );

ALTER TABLE FIELD ADD(
    FOREIGN KEY (OWNER_HP) REFERENCES OWNER (OWNER_HP) ON DELETE CASCADE
    );

COMMIT;